skipsdist = true

envlist = ["unused-code", "unittests"]

[env.unused-code]
deps = ["python-utility-scripts"]
commands = [["pyutils-unusedcode", "--exclude-files", "conftest.py"]]

[env.unittests]
deps = ["uv"]
commands = [["uv", "run", "--group", "tests", "pytest", "-n", "auto", "tests"]]
